### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thomas-kuntz**
I think this is better 😉

### CODE REVIEW

**Comment by thomas-kuntz** [comment]
So, how about just merging this in? 😜

**Comment by thomas-kuntz** [comment]
Looks good to me!

**Comment by johanmaillet** [comment]
what about marriage ??

**Comment by johanmaillet** [comment]
Are you really saying no to this beautiful and perfect wedding demand? You're such an heartless man...

**Comment by thomas-kuntz** [comment]
Yes I am. How about dealing with this pull request for real now?

**Pull request merged**
