### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by johanmaillet**
hi guys what do you think about these changes.

### CODE REVIEW

**Comment by thomas-kuntz** [comment]
This is crap!!! 😃

**Comment by thomas-kuntz** [comment]
🖕🖕🖕

**Comment by thomas-kuntz** [comment]
Just kidding, good job! Keep on learning, bro! 👍

**Comment by johanmaillet** [comment]
my change reallly improve the project, please take a look before to say that's crap

**Comment by thomas-kuntz** [comment]
Looks good to me! (LGTM)

I did take a look, I think you're ready to merge!

**Pull request merged**
